import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { broadcastUpdate } from '@/lib/sse'

const COUNTRIES = [
  { name: 'Zorblax', color: '#dc2626', motto: 'We Peaked Centuries Ago', story: 'Zorblax was once the crown jewel of the galaxy — towering intellect, breathtaking architecture, remarkable cuisine. That was 400 years ago. Today, Zorblax coasts entirely on its historical reputation, issuing lengthy press releases about past achievements and sending strongly-worded letters to anyone who questions their relevance. They distributed millions of GSBF-7 forms to Plumeria, Blargh, Gloopiter, and Snorvia, insisting all trade go through proper channels. The forms were so complex that trade ground to a halt for three years. Relations remain complicated.', famousFor: 'Zorblax invented the Galactic Standard Bureaucratic Form (GSBF-7), a 47-page document required for any inter-planetary transaction. They are extremely proud of this. No one else is.', food: 8, wealth: 10, environment: 2, kushBalls: 6, relations: { rightOn: ['Veluptia','Cramdor'], allRight: ['Fizznak','Quorb','Snorvia'], writeOff: ['Plumeria','Blargh','Gloopiter','Mertox'] }, promises: [{ resource: 'food', target: 3, byYear: 5 }, { resource: 'wealth', target: 8, byYear: 5 }, { resource: 'environment', target: 5, byYear: 4 }] },
  { name: 'Plumeria', color: '#eab308', motto: 'Technically Not Our Fault', story: 'Plumerians are a cheerful, outdoorsy people who built an entire civilization around extreme sports and elaborate excuses. Their legal system consists entirely of liability waivers. Cramdor, Blargh, Mertox, and Veluptia placed enormous orders for Gravity Flakes. Their space stations were rendered inoperable for months due to cereal expansion incidents. Plumeria\'s statement noted the instructions "clearly stated zero-gravity not recommended." The instructions did not say this.', famousFor: 'Gravity Flakes — a breakfast cereal that, consumed in zero-gravity, expands to 40 times its original size. Marketed as "the snack that fills you up." It filled up several cargo bays instead.', food: 10, wealth: 3, environment: 6, kushBalls: 4, relations: { rightOn: ['Fizznak','Quorb'], allRight: ['Snorvia','Gloopiter','Zorblax'], writeOff: ['Veluptia','Blargh','Cramdor','Mertox'] }, promises: [{ resource: 'food', target: 8, byYear: 5 }, { resource: 'wealth', target: 1, byYear: 5 }, { resource: 'environment', target: 1, byYear: 5 }] },
  { name: 'Snorvia', color: '#166534', motto: 'We Remember Everything. Everything.', story: 'Snorvia is home to the galaxy\'s largest archive of grudges, meticulously catalogued and cross-referenced. Snorvians have photographic memory and an ancestral commitment to holding onto slights across generations. Plumeria, Mertox, Blargh, and Gloopiter ordered millions of copies of "The Little Book of Planetary Blunders." A chapter titled "The Top 10 Dumbest Things Your Planet Ever Did" caused immediate diplomatic incidents.', famousFor: '"The Little Book of Planetary Blunders" — a children\'s guide to other civilizations\' most embarrassing historical mistakes, with illustrations. It was meant warmly. It was not received warmly.', food: 8, wealth: 10, environment: 2, kushBalls: 6, relations: { rightOn: ['Veluptia','Cramdor'], allRight: ['Fizznak','Quorb','Zorblax'], writeOff: ['Plumeria','Blargh','Gloopiter','Mertox'] }, promises: [{ resource: 'food', target: 3, byYear: 5 }, { resource: 'wealth', target: 8, byYear: 5 }, { resource: 'environment', target: 5, byYear: 4 }] },
  { name: 'Blargh', color: '#ec4899', motto: 'Whatever You Need, Darling', story: 'Blargh is the galaxy\'s premier resort destination — crystalline oceans, seventeen moons, a hospitality industry so aggressively pleasant it makes visitors mildly uncomfortable. Their economy is built on tourism and saying yes to absolutely everything. Plumeria, Zorblax, Snorvia, Fizznak, Gloopiter, and Quorb placed bulk orders for Shadowbloom seeds. Within one season, space stations were structurally compromised by plant growth. Six planets spent fortunes on removal. Blargh issued a wellness newsletter about "embracing nature." The lawsuits are ongoing.', famousFor: 'The Blargh Shadowbloom — a rapidly growing space plant providing shade for beach resorts. It also grows through hull plating and reproduces every 72 hours. Details were not disclosed in the brochure.', food: 1, wealth: 1, environment: 18, kushBalls: 8, relations: { rightOn: [], allRight: ['Veluptia','Cramdor','Mertox'], writeOff: ['Plumeria','Gloopiter','Fizznak','Quorb','Zorblax','Snorvia'] }, promises: [{ resource: 'food', target: 8, byYear: 2 }, { resource: 'wealth', target: 4, byYear: 3 }, { resource: 'environment', target: 6, byYear: 4 }] },
  { name: 'Mertox', color: '#4ade80', motto: 'The Good, The Sustainable, The Smug', story: 'Mertox is a beacon of environmental consciousness, renewable energy, and unsolicited advice. Mertoxians compost everything, including their opinions, which they redistribute as fertilizer for other planets\' "intellectual growth." Mertox invited Plumeria, Zorblax, Snorvia, Fizznak, Gloopiter, and Quorb on a sponsored "Wellness Delegation" tour. The trip ended when several governors requested a meal with actual protein. Mertox filed an official complaint about "nutritional imperialism."', famousFor: 'The Cosmic Nutri-Pod — a nutrient capsule combining the flavours of seventeen vegetables into one sustainable snack. Six planets ordered it. It tasted exactly like sadness compressed into a pellet.', food: 1, wealth: 1, environment: 18, kushBalls: 8, relations: { rightOn: [], allRight: ['Veluptia','Cramdor','Blargh'], writeOff: ['Plumeria','Gloopiter','Fizznak','Quorb','Zorblax','Snorvia'] }, promises: [{ resource: 'food', target: 8, byYear: 2 }, { resource: 'wealth', target: 4, byYear: 3 }, { resource: 'environment', target: 6, byYear: 4 }] },
  { name: 'Fizznak', color: '#7c3aed', motto: 'Bold, True, and Slightly Radioactive', story: 'Fizznak is a planet of industry, large families, and spectacular stained-glass architecture — making their cities look like enormous decorative lampshades. Fizznakians are loyal, loud, and have an inexplicable tradition of naming their children after spacecraft components. Cramdor, Blargh, Mertox, and Veluptia each commissioned stained-glass spacecraft. The vessels were magnificent. They shattered upon re-entry. Fizznak disputed that "re-entry durability" was ever part of the spec.', famousFor: 'Fizznak\'s stained glass appears in cathedrals, government buildings, and luxury yachts across the galaxy. They also branched into stained-glass-hulled spacecraft, which were beautiful and almost entirely non-functional as spacecraft.', food: 6, wealth: 1, environment: 4, kushBalls: 5, relations: { rightOn: ['Plumeria','Gloopiter'], allRight: ['Quorb','Zorblax','Snorvia'], writeOff: ['Blargh','Veluptia','Cramdor','Mertox'] }, promises: [{ resource: 'food', target: 3, byYear: 5 }, { resource: 'wealth', target: 2, byYear: 5 }, { resource: 'environment', target: 7, byYear: 4 }] },
  { name: 'Quorb', color: '#f97316', motto: 'We Need Only Us (And Possibly A Trade Deal)', story: 'Quorb is a fiercely independent planet of mountain peaks, tropical flowers, and an entire species of pets that are inexplicably also government officials. Quorbians are warm to each other and deeply suspicious of outsiders. Their immigration form is 200 pages. Page 198 asks if you have "vibes." Mertox, Veluptia, Cramdor, and Blargh placed large orders for BarkTranslator Collars. The collars worked perfectly. The translated communications from their own pets were so alarming that two planetary governments faced internal revolts.', famousFor: 'The BarkTranslator Collar — converts pet communications into recognizable words. It works. This has caused significant political complications, as several Quorbian cabinet ministers are dogs who now have strong opinions about trade policy.', food: 6, wealth: 1, environment: 4, kushBalls: 5, relations: { rightOn: ['Plumeria','Gloopiter'], allRight: ['Fizznak','Zorblax','Snorvia'], writeOff: ['Blargh','Veluptia','Cramdor','Mertox'] }, promises: [{ resource: 'food', target: 3, byYear: 5 }, { resource: 'wealth', target: 2, byYear: 5 }, { resource: 'environment', target: 7, byYear: 4 }] },
  { name: 'Gloopiter', color: '#2563eb', motto: 'The Rewarded (By Ourselves, For Ourselves)', story: 'Gloopiter is a planet of vast fertile plains, enormous coastlines, and a technology sector so advanced it has become entirely incomprehensible to the other nine planets. Gloopiterians are polite, enormously wealthy, and mildly astonished that everyone else hasn\'t figured things out yet. Veluptia, Mertox, Blargh, and Cramdor imported Ageless Mirrors by the millions. Economic output dropped 40%. Several elections were decided entirely by how good candidates looked in their mirrors.', famousFor: 'The Ageless Mirror — lets users choose how old they appear in their reflection. The technology was flawless. The four planets that imported it experienced a complete societal collapse of vanity-related productivity. Everyone spent 6 hours a day looking at themselves.', food: 10, wealth: 3, environment: 6, kushBalls: 4, relations: { rightOn: ['Quorb','Fizznak'], allRight: ['Plumeria','Zorblax','Snorvia'], writeOff: ['Blargh','Veluptia','Cramdor','Mertox'] }, promises: [{ resource: 'food', target: 8, byYear: 5 }, { resource: 'wealth', target: 1, byYear: 5 }, { resource: 'environment', target: 1, byYear: 5 }] },
  { name: 'Veluptia', color: '#94a3b8', motto: 'Sing A Song (Invoice To Follow)', story: 'Veluptia is the cultural capital of the galaxy — theatre, musicals, opera, interpretive zero-gravity dance. Every planet wants Veluptian performers. Veluptians know this and have priced accordingly. Plumeria, Fizznak, Quorb, and Gloopiter bought out the entire performance run. Audiences talked, ate loudly, and a Plumerian governor snored audibly during the finale. Veluptia\'s tabloids ran "Barbaric Foreigners Ruin Art" for six consecutive weeks.', famousFor: 'Veluptia announced a galaxy-wide "Week of Performances" — a touring spectacular. The performances were transcendent. The audience behavior was described as "catastrophically rude." A seven-part documentary was produced. It won seventeen awards.', food: 1, wealth: 5, environment: 2, kushBalls: 3, relations: { rightOn: ['Zorblax','Mertox','Snorvia','Blargh'], allRight: ['Cramdor'], writeOff: ['Plumeria','Fizznak','Quorb','Gloopiter'] }, promises: [{ resource: 'food', target: 2, byYear: 5 }, { resource: 'wealth', target: 1, byYear: 5 }, { resource: 'environment', target: 12, byYear: 3 }] },
  { name: 'Cramdor', color: '#7dd3fc', motto: 'To Defend and Snack', story: 'Cramdor is a boisterous, fun-loving planet famous for miniature collectible figurines and a disproportionate military history for their size. Cramdorians are warm hosts, enthusiastic traders, and deeply committed to the bit. Plumeria, Fizznak, Quorb, and Gloopiter ordered millions of sets of autonomous miniature robot soldiers. Within weeks, the tiny armies marched out of toy boxes and began "occupying" kitchen counters, communications equipment, and a planetary defence console. Cramdor\'s legal position: the robots were "acting within their programming."', famousFor: 'Boxed sets of fully autonomous miniature robot soldiers — each unit independently operational, historically accurate, and approximately 4 centimeters tall. A sensation, until they started acting independently.', food: 1, wealth: 5, environment: 2, kushBalls: 3, relations: { rightOn: ['Zorblax','Mertox','Snorvia','Blargh'], allRight: ['Veluptia'], writeOff: ['Plumeria','Fizznak','Quorb','Gloopiter'] }, promises: [{ resource: 'food', target: 2, byYear: 5 }, { resource: 'wealth', target: 1, byYear: 5 }, { resource: 'environment', target: 12, byYear: 3 }] },
]

export async function POST(req: Request) {
  const body = await req.json()
  if (body.password !== 'admin123') {
    return NextResponse.json({ error: 'Invalid password' }, { status: 401 })
  }

  // Clean up old sessions
  await prisma.debriefResponse.deleteMany()
  await prisma.promiseCheck.deleteMany()
  await prisma.scandalAlliance.deleteMany()
  await prisma.scandal.deleteMany()
  await prisma.trade.deleteMany()
  await prisma.country.deleteMany()
  await prisma.session.deleteMany()

  const session = await prisma.session.create({
    data: {
      year: 1,
      phase: 'TRADING',
      countries: {
        create: COUNTRIES.map(c => ({
          name: c.name,
          color: c.color,
          motto: c.motto,
          story: c.story,
          famousFor: c.famousFor,
          food: c.food,
          wealth: c.wealth,
          environment: c.environment,
          kushBalls: c.kushBalls,
          relationsData: JSON.stringify(c.relations),
          promisesData: JSON.stringify(c.promises)
        }))
      }
    },
    include: { countries: true }
  })

  broadcastUpdate(session.id, { type: 'SESSION_CREATED', session })
  return NextResponse.json(session)
}
